feat: Added PR template.
SituDevelopment/.github pull request #58
Opened 2024-01-30 06:24 UTC by andre-at-situ

How tested?

This is the test lolz :)

2024-01-30 08:10 UTC, willsawyerrrr commented on .github/pull_request_template.md
> +- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
This information is conveyed through a label on the pull request and its associated issue (if any).

2024-01-30 08:10 UTC, willsawyerrrr commented on .github/pull_request_template.md
> +If the change is breaking, describe the actions taken to update those packages/repos that depend on this repo:
This is only relevant to libraries. These actions should be described in their release notes, not in a pull request.

2024-01-30 08:10 UTC, willsawyerrrr commented on .github/pull_request_template.md
> +- [ ] All build checks are passing
This requirement is enforced by status checks.

2024-01-30 08:10 UTC, willsawyerrrr commented on .github/pull_request_template.md
> +- [ ] New and existing unit tests pass locally with my changes
Locally doesn't matter, all unit tests need to pass within the status check on this PR.

2024-01-30 08:10 UTC, willsawyerrrr commented on .github/pull_request_template.md
> +- [ ] I have added tests that prove my fix is effective or that my feature works
This will be conveyed through changes in the test directory as part of this PR.

2024-01-30 08:12 UTC, willsawyerrrr commented
I'm not entirely opposed to a pull request template, though I think it needs to convey better information than this suggestion.

2024-01-30 08:13 UTC, willsawyerrrr commented
For consistency with issue templates, any pull request template(s) we create should be under the `.github/PULL_REQUEST_TEMPLATE` directory with meaningful names, not just within `.github`.

2024-01-30 22:38 UTC, andre-at-situ commented on .github/pull_request_template.md
> +- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
How does the label tell me then change is breaking and/or if the author has thought about it?

2024-01-30 22:40 UTC, andre-at-situ commented on .github/pull_request_template.md
> +If the change is breaking, describe the actions taken to update those packages/repos that depend on this repo:
For a formal library that we don't publish I agree.. but if one of us updates an internal library to effective use that change in another repo straight-away, then this information is useful.

2024-01-30 22:42 UTC, andre-at-situ commented on .github/pull_request_template.md
> +- [ ] All build checks are passing
This is a checklist. It means the author knows they should check all of the status checks.

2024-01-30 22:43 UTC, andre-at-situ commented
> For consistency with issue templates, any pull request template(s) we create should be under the `.github/PULL_REQUEST_TEMPLATE` directory with meaningful names, not just within `.github`.

I don't even know if this going to work - file locations don't need to be precise for an experiment.

2024-01-30 22:45 UTC, andre-at-situ commented on .github/pull_request_template.md
> +- [ ] I have added tests that prove my fix is effective or that my feature works
This is a checklist. It's to remind the author that they need to add tests and test their feature.

2024-01-30 22:46 UTC, andre-at-situ commented
> I'm not entirely opposed to a pull request template, though I think it needs to convey better information than this suggestion.

What do you think should be included then? What information do you want to see?

2024-01-30 22:49 UTC, andre-at-situ commented on .github/pull_request_template.md
> +- [ ] New and existing unit tests pass locally with my changes
This is a checklist and informs the reviewer that the author has thought about and has conducted testing.

2024-01-31 01:24 UTC, willsawyerrrr commented on .github/pull_request_template.md
> +If the change is breaking, describe the actions taken to update those packages/repos that depend on this repo:
Why should our internal libraries be any less formally managed and released?

2024-01-31 04:04 UTC, andre-at-situ commented on .github/pull_request_template.md
> +If the change is breaking, describe the actions taken to update those packages/repos that depend on this repo:
That wasn't what I was suggesting. The publication of release notes is a separate issue to what I've brought up here.

If someone makes a change to an internal library then I see it as their responsibility to fix and/or create issues for all the things they may break in dependent packages.

We could just address this by limiting version bumps to point releases but this isn't being very friendly to the person updating the code that depends on the library.

If someone is making a company wide library change then I'd like to see that they're thinking about the implications of the change. This is especially important with minimal test coverage.

2024-01-31 04:06 UTC, andre-at-situ commented on .github/pull_request_template.md
> +- [ ] All build checks are passing
I updated this btw. The author only knows code checks are passing once the PR is created so its unfair to ask if they pass here.

2024-02-02 10:04 UTC, willsawyerrrr commented on .github/pull_request_template.md
> +- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
Can you please explain what you mean by "breaking change" in this context?

My mind goes straight to a major version release of a product or library, which isn't relevant to most of our repositories: I think it'd only be relevant on the Automation suite, the dev container configurations, the Entegy SDK and the FastAPI starter.

If you simply mean anything which changes how the application works, that would include all fixes and features.

2024-02-08 08:47 UTC, willsawyerrrr submitted a review, later dismissed
Please move to the appropriate directory for extensibility as per https://github.com/SituDevelopment/.github/pull/58#issuecomment-1916286601. Otherwise, good to go.

2024-02-15 01:33 UTC, willsawyerrrr requested changes
https://github.com/SituDevelopment/.github/pull/58#pullrequestreview-1869567083

2024-02-19 22:54 UTC, merged